create table if not exists public.leaderboard_scores (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 16),
  score integer not null check (score >= 0),
  level integer not null default 1 check (level >= 1),
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists leaderboard_scores_score_idx
  on public.leaderboard_scores (score desc, created_at asc);
